require "http/server"
require "json"
require "../commands/version_command"

module Wgctl
  module Server
    module OpenAPISpec
      def self.generate(host : String = "localhost", port : Int32 = 7443, scheme : String = "http") : String
        version = Commands::VersionCommand::VERSION
        spec = {
          "openapi" => "3.0.3",
          "info"    => {
            "title"       => "wgctl REST API",
            "description" => "Headless REST API for managing WireGuard interfaces and peers via wgctl daemon.\n\nAuthenticate with a Bearer token generated by `wgctl daemon token create`.\n\nAll responses follow the envelope `{\"success\": true, \"data\": ...}` or `{\"success\": false, \"error\": {\"code\": ..., \"message\": ...}}`.",
            "version"     => version,
            "contact"     => {"name" => "GMNDS/wgctl", "url" => "https://github.com/GMNDS/wgctl"},
            "license"     => {"name" => "MIT"}
          },
          "servers" => [
            {"url" => "#{scheme}://#{host}:#{port}/api/v1", "description" => "wgctl daemon (local)"}
          ],
          "security" => [{"BearerAuth" => [] of String}],
          "components" => {
            "securitySchemes" => {
              "BearerAuth" => {
                "type"         => "http",
                "scheme"       => "bearer",
                "bearerFormat" => "Token",
                "description"  => "Token gerado via `wgctl daemon token create`"
              }
            },
            "schemas" => {
              "HealthResponse" => {
                "type" => "object",
                "properties" => {
                  "status"    => {"type" => "string", "example" => "ok"},
                  "version"   => {"type" => "string", "example" => version},
                  "timestamp" => {"type" => "string", "format" => "date-time"}
                }
              },
              "Interface" => {
                "type" => "object",
                "properties" => {
                  "name"              => {"type" => "string", "example" => "wg0"},
                  "address"           => {"type" => "string", "example" => "10.13.14.1/24"},
                  "listen_port"       => {"type" => "integer", "example" => 51820},
                  "public_key"        => {"type" => "string"},
                  "active"            => {"type" => "boolean"},
                  "peer_count"        => {"type" => "integer"},
                  "online_peer_count" => {"type" => "integer"},
                  "config_path"       => {"type" => "string", "example" => "/etc/wireguard/wg0.conf"}
                }
              },
              "Peer" => {
                "type" => "object",
                "properties" => {
                  "name"             => {"type" => "string", "example" => "notebook"},
                  "has_name"         => {"type" => "boolean"},
                  "public_key"       => {"type" => "string"},
                  "allowed_ips"      => {"type" => "array", "items" => {"type" => "string"}, "example" => ["10.13.14.2/32"]},
                  "primary_ip"       => {"type" => "string", "example" => "10.13.14.2/32"},
                  "description"      => {"type" => "string"},
                  "device"           => {"type" => "string", "example" => "laptop"},
                  "online"           => {"type" => "boolean"},
                  "endpoint"         => {"type" => "string", "example" => "200.1.2.3:45678", "nullable" => true},
                  "latest_handshake" => {"type" => "string", "format" => "date-time", "nullable" => true},
                  "transfer_rx"      => {"type" => "integer", "example" => 1048576},
                  "transfer_tx"      => {"type" => "integer", "example" => 2097152}
                }
              },
              "AddPeerRequest" => {
                "type"     => "object",
                "required" => ["name"],
                "properties" => {
                  "name"        => {"type" => "string", "description" => "Nome único do peer", "example" => "cel-joao"},
                  "public_key"  => {"type" => "string", "description" => "Chave pública do cliente. Se omitido, o servidor gera o par de chaves (modo managed)."},
                  "ip"          => {"type" => "string", "description" => "IP a alocar. 'auto' para o próximo livre.", "default" => "auto", "example" => "auto"},
                  "device"      => {"type" => "string", "description" => "Tipo de dispositivo", "enum" => ["phone", "laptop", "pc", "server"], "default" => "device"},
                  "description" => {"type" => "string", "description" => "Descrição livre"},
                  "keepalive"   => {"type" => "integer", "description" => "PersistentKeepalive em segundos", "default" => 25}
                }
              },
              "EditPeerRequest" => {
                "type" => "object",
                "properties" => {
                  "name"        => {"type" => "string"},
                  "description" => {"type" => "string"},
                  "device"      => {"type" => "string"},
                  "ip"          => {"type" => "string"},
                  "keepalive"   => {"type" => "integer"}
                }
              },
              "ClientConfig" => {
                "type" => "object",
                "properties" => {
                  "name"     => {"type" => "string"},
                  "filename" => {"type" => "string", "example" => "notebook.conf"},
                  "config"   => {"type" => "string", "description" => "Conteúdo do arquivo .conf WireGuard"}
                }
              },
              "PeerQR" => {
                "type" => "object",
                "properties" => {
                  "name"    => {"type" => "string"},
                  "config"  => {"type" => "string"},
                  "qr_text" => {"type" => "string", "nullable" => true, "description" => "QR code ASCII para o app WireGuard"}
                }
              },
              "CheckReport" => {
                "type" => "object",
                "properties" => {
                  "valid"  => {"type" => "boolean"},
                  "issues" => {
                    "type"  => "array",
                    "items" => {
                      "type" => "object",
                      "properties" => {
                        "severity" => {"type" => "string", "enum" => ["error", "warning", "info"]},
                        "message"  => {"type" => "string"}
                      }
                    }
                  }
                }
              },
              "Error" => {
                "type" => "object",
                "properties" => {
                  "success" => {"type" => "boolean", "example" => false},
                  "error"   => {
                    "type" => "object",
                    "properties" => {
                      "code"    => {"type" => "string", "example" => "PEER_NOT_FOUND"},
                      "message" => {"type" => "string"}
                    }
                  }
                }
              }
            },
            "responses" => {
              "Unauthorized" => {
                "description" => "Token ausente, inválido ou expirado",
                "content"     => {"application/json" => {"schema" => {"$ref" => "#/components/schemas/Error"}}}
              },
              "NotFound" => {
                "description" => "Recurso não encontrado",
                "content"     => {"application/json" => {"schema" => {"$ref" => "#/components/schemas/Error"}}}
              },
              "InternalError" => {
                "description" => "Erro interno do servidor",
                "content"     => {"application/json" => {"schema" => {"$ref" => "#/components/schemas/Error"}}}
              }
            }
          },
          "paths" => {
            "/health" => {
              "get" => {
                "tags"        => ["Health"],
                "summary"     => "Status do daemon",
                "description" => "Verifica se o daemon está operacional. Não requer autenticação.",
                "security"    => [] of String,
                "responses"   => {
                  "200" => {
                    "description" => "Daemon operacional",
                    "content"     => {
                      "application/json" => {
                        "schema" => {
                          "type" => "object",
                          "properties" => {
                            "success" => {"type" => "boolean"},
                            "data"    => {"$ref" => "#/components/schemas/HealthResponse"}
                          }
                        }
                      }
                    }
                  }
                }
              }
            },
            "/interfaces" => {
              "get" => {
                "tags"      => ["Interfaces"],
                "summary"   => "Listar interfaces WireGuard",
                "responses" => {
                  "200" => {
                    "description" => "Lista de nomes de interfaces",
                    "content"     => {
                      "application/json" => {
                        "schema" => {
                          "type" => "object",
                          "properties" => {
                            "success" => {"type" => "boolean"},
                            "data"    => {"type" => "array", "items" => {"type" => "string"}, "example" => ["wg0", "wg1"]}
                          }
                        }
                      }
                    }
                  },
                  "401" => {"$ref" => "#/components/responses/Unauthorized"}
                }
              }
            },
            "/interfaces/{name}" => {
              "parameters" => [
                {"name" => "name", "in" => "path", "required" => true, "schema" => {"type" => "string"}, "description" => "Nome da interface (ex: wg0)"}
              ],
              "get" => {
                "tags"      => ["Interfaces"],
                "summary"   => "Detalhes de uma interface",
                "responses" => {
                  "200" => {
                    "description" => "Dados da interface",
                    "content"     => {"application/json" => {"schema" => {"type" => "object", "properties" => {"success" => {"type" => "boolean"}, "data" => {"$ref" => "#/components/schemas/Interface"}}}}}
                  },
                  "401" => {"$ref" => "#/components/responses/Unauthorized"},
                  "404" => {"$ref" => "#/components/responses/NotFound"}
                }
              }
            },
            "/interfaces/{name}/apply" => {
              "parameters" => [
                {"name" => "name", "in" => "path", "required" => true, "schema" => {"type" => "string"}}
              ],
              "post" => {
                "tags"        => ["Interfaces"],
                "summary"     => "Aplicar configuração ao kernel",
                "description" => "Equivalente a `wg syncconf`. Aplica a configuração atual sem reiniciar a interface.",
                "responses"   => {
                  "200" => {
                    "description" => "Configuração aplicada",
                    "content"     => {"application/json" => {"schema" => {"type" => "object", "properties" => {"success" => {"type" => "boolean"}, "data" => {"type" => "object", "properties" => {"applied" => {"type" => "boolean"}, "message" => {"type" => "string"}}}}}}}
                  },
                  "401" => {"$ref" => "#/components/responses/Unauthorized"},
                  "404" => {"$ref" => "#/components/responses/NotFound"},
                  "500" => {"$ref" => "#/components/responses/InternalError"}
                }
              }
            },
            "/interfaces/{name}/check" => {
              "parameters" => [
                {"name" => "name", "in" => "path", "required" => true, "schema" => {"type" => "string"}}
              ],
              "get" => {
                "tags"      => ["Interfaces"],
                "summary"   => "Validar e diagnosticar configuração",
                "responses" => {
                  "200" => {
                    "description" => "Relatório de validação",
                    "content"     => {"application/json" => {"schema" => {"type" => "object", "properties" => {"success" => {"type" => "boolean"}, "data" => {"$ref" => "#/components/schemas/CheckReport"}}}}}
                  },
                  "401" => {"$ref" => "#/components/responses/Unauthorized"},
                  "404" => {"$ref" => "#/components/responses/NotFound"}
                }
              }
            },
            "/interfaces/{name}/peers" => {
              "parameters" => [
                {"name" => "name", "in" => "path", "required" => true, "schema" => {"type" => "string"}}
              ],
              "get" => {
                "tags"      => ["Peers"],
                "summary"   => "Listar peers",
                "responses" => {
                  "200" => {
                    "description" => "Lista de peers",
                    "content"     => {"application/json" => {"schema" => {"type" => "object", "properties" => {"success" => {"type" => "boolean"}, "data" => {"type" => "array", "items" => {"$ref" => "#/components/schemas/Peer"}}}}}}
                  },
                  "401" => {"$ref" => "#/components/responses/Unauthorized"},
                  "404" => {"$ref" => "#/components/responses/NotFound"}
                }
              },
              "post" => {
                "tags"        => ["Peers"],
                "summary"     => "Adicionar peer",
                "description" => "Adiciona um novo peer à interface.\n\n**Modo managed** (padrão): o servidor gera o par de chaves. A chave privada do cliente é retornada uma única vez na resposta.\n\n**Modo zero-knowledge**: forneça `public_key` com a chave pública do cliente. O servidor nunca vê a chave privada.",
                "requestBody" => {
                  "required" => true,
                  "content"  => {"application/json" => {"schema" => {"$ref" => "#/components/schemas/AddPeerRequest"}}}
                },
                "responses" => {
                  "201" => {
                    "description" => "Peer adicionado com sucesso",
                    "content"     => {
                      "application/json" => {
                        "schema" => {
                          "type" => "object",
                          "properties" => {
                            "success" => {"type" => "boolean"},
                            "data" => {
                              "type" => "object",
                              "properties" => {
                                "name"          => {"type" => "string"},
                                "public_key"    => {"type" => "string"},
                                "allowed_ips"   => {"type" => "array", "items" => {"type" => "string"}},
                                "mode"          => {"type" => "string", "enum" => ["managed", "zero_knowledge"]},
                                "client_config" => {"type" => "string"},
                                "qr_text"       => {"type" => "string", "nullable" => true}
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "400" => {"$ref" => "#/components/responses/NotFound"},
                  "401" => {"$ref" => "#/components/responses/Unauthorized"},
                  "404" => {"$ref" => "#/components/responses/NotFound"},
                  "409" => {
                    "description" => "Nome ou IP já existente",
                    "content"     => {"application/json" => {"schema" => {"$ref" => "#/components/schemas/Error"}}}
                  }
                }
              }
            },
            "/interfaces/{name}/peers/{key}" => {
              "parameters" => [
                {"name" => "name", "in" => "path", "required" => true, "schema" => {"type" => "string"}, "description" => "Nome da interface"},
                {"name" => "key", "in" => "path", "required" => true, "schema" => {"type" => "string"}, "description" => "Nome do peer ou chave pública (URL-encoded)"}
              ],
              "get" => {
                "tags"      => ["Peers"],
                "summary"   => "Detalhes de um peer",
                "responses" => {
                  "200" => {
                    "description" => "Dados do peer",
                    "content"     => {"application/json" => {"schema" => {"type" => "object", "properties" => {"success" => {"type" => "boolean"}, "data" => {"$ref" => "#/components/schemas/Peer"}}}}}
                  },
                  "401" => {"$ref" => "#/components/responses/Unauthorized"},
                  "404" => {"$ref" => "#/components/responses/NotFound"}
                }
              },
              "patch" => {
                "tags"        => ["Peers"],
                "summary"     => "Editar peer",
                "description" => "Atualiza campos de um peer. Apenas os campos enviados são alterados. `PUT` também é aceito.",
                "requestBody" => {
                  "required" => false,
                  "content"  => {"application/json" => {"schema" => {"$ref" => "#/components/schemas/EditPeerRequest"}}}
                },
                "responses" => {
                  "200" => {
                    "description" => "Peer atualizado",
                    "content"     => {"application/json" => {"schema" => {"type" => "object", "properties" => {"success" => {"type" => "boolean"}, "data" => {"$ref" => "#/components/schemas/Peer"}}}}}
                  },
                  "401" => {"$ref" => "#/components/responses/Unauthorized"},
                  "404" => {"$ref" => "#/components/responses/NotFound"},
                  "409" => {
                    "description" => "Conflito (nome ou IP já existente)",
                    "content"     => {"application/json" => {"schema" => {"$ref" => "#/components/schemas/Error"}}}
                  }
                }
              },
              "delete" => {
                "tags"      => ["Peers"],
                "summary"   => "Remover peer",
                "responses" => {
                  "200" => {
                    "description" => "Peer removido",
                    "content"     => {"application/json" => {"schema" => {"type" => "object", "properties" => {"success" => {"type" => "boolean"}, "data" => {"type" => "object", "properties" => {"message" => {"type" => "string"}}}}}}}
                  },
                  "401" => {"$ref" => "#/components/responses/Unauthorized"},
                  "404" => {"$ref" => "#/components/responses/NotFound"}
                }
              }
            },
            "/interfaces/{name}/peers/{key}/config" => {
              "parameters" => [
                {"name" => "name", "in" => "path", "required" => true, "schema" => {"type" => "string"}},
                {"name" => "key", "in" => "path", "required" => true, "schema" => {"type" => "string"}}
              ],
              "get" => {
                "tags"        => ["Peers"],
                "summary"     => "Arquivo .conf do cliente",
                "description" => "Retorna a configuração WireGuard pronta para o dispositivo cliente.\n\nUse `Accept: text/plain` para baixar o arquivo `.conf` diretamente.",
                "parameters"  => [
                  {"name" => "name", "in" => "path", "required" => true, "schema" => {"type" => "string"}},
                  {"name" => "key", "in" => "path", "required" => true, "schema" => {"type" => "string"}}
                ],
                "responses" => {
                  "200" => {
                    "description" => "Configuração do cliente",
                    "content"     => {
                      "application/json" => {"schema" => {"type" => "object", "properties" => {"success" => {"type" => "boolean"}, "data" => {"$ref" => "#/components/schemas/ClientConfig"}}}},
                      "text/plain"       => {"schema" => {"type" => "string"}}
                    }
                  },
                  "401" => {"$ref" => "#/components/responses/Unauthorized"},
                  "404" => {"$ref" => "#/components/responses/NotFound"}
                }
              }
            },
            "/interfaces/{name}/peers/{key}/qr" => {
              "parameters" => [
                {"name" => "name", "in" => "path", "required" => true, "schema" => {"type" => "string"}},
                {"name" => "key", "in" => "path", "required" => true, "schema" => {"type" => "string"}}
              ],
              "get" => {
                "tags"      => ["Peers"],
                "summary"   => "QR Code do cliente",
                "responses" => {
                  "200" => {
                    "description" => "QR Code ASCII e configuração",
                    "content"     => {"application/json" => {"schema" => {"type" => "object", "properties" => {"success" => {"type" => "boolean"}, "data" => {"$ref" => "#/components/schemas/PeerQR"}}}}}
                  },
                  "401" => {"$ref" => "#/components/responses/Unauthorized"},
                  "404" => {"$ref" => "#/components/responses/NotFound"}
                }
              }
            }
          }
        }

        spec.to_json
      end

      SWAGGER_UI_HTML = <<-HTML
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>wgctl API Docs</title>
        <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
        <style>
          body { margin: 0; background: #fafafa; }
          .topbar { display: none !important; }
          .swagger-ui .info { margin: 20px 0; }
        </style>
      </head>
      <body>
        <div id="swagger-ui"></div>
        <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
        <script>
          SwaggerUIBundle({
            url: window.location.origin + "/api/v1/openapi.json",
            dom_id: '#swagger-ui',
            presets: [SwaggerUIBundle.presets.apis, SwaggerUIBundle.SwaggerUIStandalonePreset],
            layout: "BaseLayout",
            deepLinking: true,
            tryItOutEnabled: true,
            requestInterceptor: function(req) {
              // Preserve Authorization header set by user in the UI
              return req;
            }
          });
        </script>
      </body>
      </html>
      HTML
    end
  end
end
