changelog:
  categories:
    - title: "🚀 Features & Improvements"
      labels:
        - "feat"
        - "feature"
        - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "fix"
        - "bug"
        - "hotfix"
    - title: "🧰 Maintenance & Chores"
      labels:
        - "chore"
        - "refactor"
        - "deps"
        - "ci"
        - "documentation"
        - "doc"
