changelog:
  categories:
    - title: "Novidades e Melhorias"
      labels:
        - "feat"
        - "feature"
        - "enhancement"
    - title: "Correções de Bugs"
      labels:
        - "fix"
        - "bug"
        - "hotfix"
    - title: "Manutenção e Tarefas"
      labels:
        - "chore"
        - "refactor"
        - "deps"
        - "ci"
        - "documentation"
        - "doc"
