[Interface]
Address = 10.13.14.1/24
ListenPort = 51823
PrivateKey = wBE64BHskDhVYR8fZSatxJaLKzGj4n9O8yxFNoN2u0c=

# wgctl:name=asteri-c
# wgctl:description=Contabo Germany
# wgctl:device=server
[Peer]
PublicKey = AsteriCPublicKeyBase64StringForTesting123456=
AllowedIPs = 10.13.14.9/32

# wgctl:name=pc
[Peer]
PublicKey = PcPublicKeyBase64StringForTesting123456789012=
AllowedIPs = 10.13.14.2/32

# wgctl:name=mobile
[Peer]
PublicKey = MobilePublicKeyBase64StringForTesting12345678=
AllowedIPs = 10.13.14.3/32
